env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
plugins: [ "html" ]
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
